-- CreateTable
CREATE TABLE `Diamond_api` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `certificateNumber` VARCHAR(191) NOT NULL,
    `shape` VARCHAR(191) NOT NULL,
    `weight` DOUBLE NOT NULL,
    `color` VARCHAR(191) NOT NULL,
    `clarity` VARCHAR(191) NOT NULL,
    `cutGrade` VARCHAR(191) NOT NULL,
    `polish` VARCHAR(191) NOT NULL,
    `symmetry` VARCHAR(191) NOT NULL,
    `fluoIntensity` VARCHAR(191) NOT NULL,
    `fluoColor` VARCHAR(191) NOT NULL,
    `rapDiscount` DOUBLE NOT NULL,
    `depthPercent` DOUBLE NOT NULL,
    `tablePercent` DOUBLE NOT NULL,
    `measLength` DOUBLE NOT NULL,
    `measWidth` DOUBLE NOT NULL,
    `measDepth` DOUBLE NOT NULL,
    `girdleSizeMin` DOUBLE NOT NULL,
    `location` VARCHAR(191) NOT NULL,
    `girdleSizeMax` DOUBLE NOT NULL,
    `finalPrice` DOUBLE NOT NULL,
    `culetSize` VARCHAR(191) NOT NULL,
    `culetCondition` VARCHAR(191) NOT NULL,
    `imageUrl` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
