name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Adjust if your build script is different

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: 9FIICJcHGO01Gfja9Hkcgo2x
          vercel-org-id: team_o0AZJcv2Ae0jjGD5TkRgXfV2
          vercel-project-id: prj_IsdAhWLY7rs4ZGYLWnIUy7RvV6jt
          vercel-args: '--prod'
